# Default Deny — Frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-frontend
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    {{- include "medimesh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      tier: frontend
  policyTypes:
    - Ingress
    - Egress
---
# Default Deny — Backend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-backend
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    {{- include "medimesh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      tier: backend
  policyTypes:
    - Ingress
    - Egress
---
# Default Deny — Database
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-db
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    {{- include "medimesh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      tier: database
  policyTypes:
    - Ingress
    - Egress
