# Shared ConfigMap — service URLs
apiVersion: v1
kind: ConfigMap
metadata:
  name: medimesh-config
  namespace: medimesh
  labels:
    {{- include "medimesh.labels" . | nindent 4 }}
data:
  NODE_ENV: "{{ .Values.global.environment }}"
  MONGO_HOST: "{{ .Values.global.mongo.host }}"
  MONGO_PORT: "{{ .Values.global.mongo.port }}"
  AUTH_SERVICE_URL: "http://medimesh-auth-svc.medimesh.svc.cluster.local:5001"
  USER_SERVICE_URL: "http://medimesh-user-svc.medimesh.svc.cluster.local:5002"
  DOCTOR_SERVICE_URL: "http://medimesh-doctor-svc.medimesh.svc.cluster.local:5003"
  APPOINTMENT_SERVICE_URL: "http://medimesh-appointment-svc.medimesh.svc.cluster.local:5004"
  VITALS_SERVICE_URL: "http://medimesh-vitals-svc.medimesh.svc.cluster.local:5005"
  PHARMACY_SERVICE_URL: "http://medimesh-pharmacy-svc.medimesh.svc.cluster.local:5006"
  AMBULANCE_SERVICE_URL: "http://medimesh-ambulance-svc.medimesh.svc.cluster.local:5007"
  COMPLAINT_SERVICE_URL: "http://medimesh-complaint-svc.medimesh.svc.cluster.local:5008"
  FORUM_SERVICE_URL: "http://medimesh-forum-svc.medimesh.svc.cluster.local:5009"
  BFF_SERVICE_URL: "http://medimesh-bff-svc.medimesh.svc.cluster.local:5010"