# MongoDB Secret (credentials for database namespace)
apiVersion: v1
kind: Secret
metadata:
  name: medimesh-mongo-secret
  namespace: {{ .Values.global.namespaces.db }}
  labels:
    app: {{ .Values.name }}
    tier: database
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.global.secrets.mongoRootUsername }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.global.secrets.mongoRootPassword }}
