name: "CI — medimesh-frontend"

on:
  push:
    branches: [main, feature/ci-pipeline-v3]
    paths:
      - "medimesh-frontend/**"
      - ".github/workflows/ci-medimesh-frontend.yml"
      - ".github/workflows/template-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "medimesh-frontend/**"
      - ".github/workflows/ci-medimesh-frontend.yml"
      - ".github/workflows/template-ci.yml"

permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/template-ci.yml
    with:
      service_name: medimesh-frontend
      service_path: medimesh-frontend
      docker_image_name: medimesh_medimesh-frontend
      sonar_project_key: medimesh-frontend
      node_version: "20"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}